import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { ModeToggle } from "@/components/mode-toggle"
import LeftSidebar from "@/components/left-sidebar"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("", inter.variable)}>
        <div className="min-h-screen bg-background font-sans antialiased flex flex-col items-center justify-between p-4">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LeftSidebar />
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  )
}
